### PR TITLE
PCL support fixed

### PR DESCRIPTION
**Pull request by npodbielski**
PCL in latest version of TinyIoC is broken (it does not compile). 
I added 2 projects (PCL projects uses newer version then projects with TinyIoC.cs) fixed errors, fixed support to all features (even if TinyMessanger and Web extensions are separate packages) and fixed all tests for PCL (the same tests as for old TinyIoC project). It would be nice to add it to repo and roll out new packages version. 
I really enjoy using Tiny and lack of PCL support always bugged me.
It would be really good to add nuget package installation script to take care of #def #undef directives.
Also it would be good in the future to use less of reflection and more compiled expressions and/or delegates. I believe it would boost performance.

### CODE REVIEW

**Comment by niemyjski** [comment]
I'd recommend closing this pr, it does way more than just do the fixes required here. And it is currently compiling and working (some references may be needed as shown here https://github.com/exceptionless/Exceptionless.Net/blob/v4.0.2/src/Exceptionless/project.json)

**Comment by npodbielski** [comment]
Yep. I agree. There is absolutely no point in left it hanging indefinitely since it never will be merged. 
I recommend also stating that TinyIoC is still incompatible with **any** version of PCL projects in readme file and in wiki, to cut all future doubts in the matter, anyone could have. 👍

**Comment by niemyjski** [comment]
Can we update or close the pr. I now have merge access :) Can we relook what it's going to take for pcl as I currently have it running as pcl with minimum changes.

**Comment by npodbielski** [comment]
I don't know. For few years I've been using my own version. On the other side PCL will become obsolete in near future. 
Do what you think is best.

**Comment by niemyjski** [comment]
It would be nice to continue to support it until it's no longer available at all nor supported.

**Comment by npodbielski** [comment]
I am under the impression that we do not understand each other. 
I am not using code from this project for more than 2 years (my private foirk - yes). I do not know if there was changes or not.
So for me you can delete or merge the pr - it does not matter for me.

**Pull request closed without merging**
