### PR TITLE
TinyIoC PCL

### PR DESCRIPTION
**Pull request by mgernand**
I added a portable class library project for TinyIoC. The PCL supports net45, sl4+, wp7.5+, WindowsStoreApps, Mono for Android and MonoTouch. Maybe it is a starting point for a official PCL release.

### CODE REVIEW

**Comment by niemyjski** [comment]
Any updates on this?

**Comment by dazinator** [comment]
Loving TinyIoC. I wish I could use it within a PCL though! Any news? If I could help, I would!

**Comment by niemyjski** [comment]
@dazinator please check out the latest code: https://github.com/grumpydev/TinyIoC/commit/361a01741a6b94583b88dcb9b71330602c59bb89 I had a big commit for this and I'm using it in our pcl library: https://github.com/exceptionless/Exceptionless.net

**Comment by dazinator** [comment]
@niemyjski oooooo nice! I'll take a look - cheers :)

**Comment by wizche** [comment]
@grumpydev any news on this pull request? Thanks ;)

**Comment by grumpydev** [comment]
@wizche : the current code works in PCL, I think this PR has been superseded.

**Comment by wizche** [comment]
@grumpydev thanks, but only if it targets .NET 4.0 right?

**Comment by grumpydev** [comment]
@wizche : nope, works on all "modern" pcl profiles - in some scenarios you need to compile it into a PCL assembly and reference it (so .net adds the reflection shims) but other than that it's fine.

**Comment by BNoohi** [comment]
Is this Pull Request still valid considering the current code works in PCL?

**Comment by niemyjski** [comment]
Yeah I'd close it my pull request added support for it

**Pull request closed without merging**
