### PR TITLE
GitHub Actions, Run on latest .NET Core SDK/macOS, new csproj, dotnet project structure

### PR DESCRIPTION
**Pull request by niemyjski**
I'm not 100% happy with the generated nuget package for three reasons

- it's listing dependencies in it (NetStandard 1.2-2.0, pcl 4.6, net45), 
- looking at the NuSpec it should be doing source includes (I'm going to merge and release a beta tag and do more testing). It's a pita to setup GitHub artifacts as it requires auth, but diffing the NuSpec it's doing the same thing.
- ASP.NET Package says it targets NetStandard 2.0 as well, needed to do that to get it to build xplat without having an extra solution file..., for some crazy reason it compiles...

The advantages to merging...

- We are now building on every commit against NetStandard 1.2-2.0, pcl, NET 4.5.
- Unit tests now run as part of the build on .NET Core and .NET 4.5
- Automatic versioning based on semver 
- Tags get automatically pushed to nuget.
- Updated project structure a bit to match greater .net community (familiarity).
- Fixed many issues and now with it building end users can see exactly what compiler flags and references they may need in the various environments.
- Updated Samples and removed old ones, verified the new ones work.

I think all of my issues listed above are minor and we can work through via a beta tag. Worst case it's possible to manually specify a NuSpec file and go back to 100% old behavior it's just not ideal, I'd rather have the tooling do all the work.

### CODE REVIEW

**Comment by niemyjski** [comment]
Still need to update the new project format to do source NuGet Packages: https://gist.github.com/attilah/fd3e71f03fd258c496179e0200c57b0b#file-x-y-z-sources-csproj  https://medium.com/@attilah/source-code-only-nuget-packages-8f34a8fb4738

**Comment by niemyjski** [comment]
It might be really tough to use the new project system to do source only includes. We'll have to figure that out. It would be dead simple if we wanted to change to non source code includes having many different project frameworks... @grumpydev please look over my last few commits. I decided to delete a bunch of really old samples / code that is just dead and you wouldn't find in the real world. Someone can do a pr for UWP, but my guess it wouldn't even be needed as it builds as .NET Standard 2.0 which the core package supports.

**Comment by grumpydev** [comment]
No problem with removing the old samples etc., but would be nice to create a named branch that still has them in before applying this PR, just so they're easily accessible if anyone does need them (don't underestimate the lifetime of old tech in enterprises 😁 )

**Comment by niemyjski** [comment]
Any good ideas for a branch name? I'm really close to merging this in. I was thinking `legacy-samples` or just doing a tag on the commit closest to the last nuget package and users can just browse by old tag. This probably would be better.

**Comment by niemyjski** [comment]
I created the https://github.com/grumpydev/TinyIoC/tree/1.3.0 1.3.0 tag for the previous release that users can browse.

**Comment by niemyjski** [comment]
@grumpydev I'm going to merge this now that the previous tag is created.  I'm not 100% happy with the generated nuget package for three reasons

- it's listing dependencies in it (NetStandard 1.2-2.0, pcl 4.6, net45), 
- looking at the NuSpec it should be doing source includes (I'm going to merge and release a beta tag and do more testing). It's a pita to setup GitHub artifacts as it requires auth, but diffing the NuSpec it's doing the same thing.
- ASP.NET Package says it targets NetStandard 2.0 as well, needed to do that to get it to build xplat without having an extra solution file..., for some crazy reason it compiles...

The advantages to merging...

- We are now building on every commit against NetStandard 1.2-2.0, pcl, NET 4.5.
- Unit tests now run as part of the build on .NET Core and .NET 4.5
- Automatic versioning based on semver 
- Tags get automatically pushed to nuget.
- Updated project structure a bit to match greater .net community (familiarity).
- Fixed many issues and now with it building end users can see exactly what compiler flags and references they may need in the various environments.
- Updated Samples and removed old ones, verified the new ones work.

I think all of my issues listed above are minor and we can work through via a beta tag. Worst case it's possible to manually specify a NuSpec file and go back to 100% old behavior it's just not ideal, I'd rather have the tooling do all the work.

**Comment by niemyjski** [comment]
Can you add me to the other Tiny packages on nuget so we can generate a nuget key with those.

**Comment by niemyjski** [comment]
@grumpydev Looks like I don't have GitHub access to add a secret. Can you create a new NuGet api key and create a GitHub secret with the name `NUGET_KEY` and the api key as the value. As well can you add me to the other Tiny packages on NuGet / create a Tiny Org and add me if you wish to be able to create GitHub secrets.

**Comment by grumpydev** [comment]
@niemyjski should be done

**Comment by niemyjski** [comment]
@grumpydev Thank you! I realize these are a lot of changes, please forgive me.

**Comment by niemyjski** [comment]
@grumpydev one last thing, should we remove TinyMessenger since it's here: https://github.com/grumpydev/TinyMessenger? I didn't diff them to see the differences.

**Comment by grumpydev** [comment]
@niemyjski I can't honestly remember which one is newer version of messenger, or if they're the same.

**Pull request merged**
