### PR TITLE
Add check for incorrect constructor used

### PR DESCRIPTION
**Pull request by richardhopton**

### CODE REVIEW

**Comment by richardhopton** [comment]
Any chance of merging this? or just close the PR if you never want to.  Thanks!

**Comment by grumpydev** [comment]
The problem I have at the moment is the version of tinyioc in nancy has diverged from this one, which was never the idea, so I need to spend some time reconciling them before I bring in any more PRs, and I haven't had time to do that yet - doesn't mean they won't get added though :)

**Comment by richardhopton** [comment]
Okay - My two PRs are adding additional tests for scenarios that caught me out when using TinyIoC so they shouldn't muddy the waters, but I understand your reluctance to merge new code.

**Comment by niemyjski** [comment]
@grumpydev @richardhopton I don't see anything wrong with this pr. I'm going to merge it in. @grumpydev where are you referring in regards to Nancy?

**Pull request merged**
